mysite/mysite/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from polls import views

urlpatterns = patterns('',
    url(r'^polls/', include('polls.urls', namespace="polls")),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^(?P<question_id>\d+)/vote/$', views.vote, name='vote'),
    url(r'^(?P<question_id>\d+)/add/$', views.add, name='add'),
)

mysite/polls/urls.py
from django.conf.urls import patterns, url
from polls import views


urlpatterns = patterns('',
    url(r'^$', views.IndexView.as_view(),
        name='index'), #ex: /polls/
    url(r'^(?P<pk>\d+)/$', views.DetailView.as_view(),
        name='detail'), #ex: /polls/5/
    url(r'^(?P<pk>\d+)/results/$', views.ResultsView.as_view(),
        name='results'),#ex: /polls/5/results
    url(r'^(?P<question_id>\d+)/vote/$', views.vote,
        name='vote'),#ex: /polls/5/vote
     url(r'^(?P<question_id>\d+)/add/$', views.add,
        name='add'),#ex: /polls/5/add
     url(r'^addq/$', views.addq,
        name='addq'),#ex: /polls/add
)

mysite/polls/models.py
import datetime

from django.db import models
from django.utils import timezone
from django import forms

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    
    def __unicode__(self):
        return self.question_text
    
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'


class Choice(models.Model):
    question = models.ForeignKey(Question)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    
    def __unicode__(self):
        return self.choice_text

    

mysite/templates/models.py
from django.db import models

# Create your models here.

mysite/polls/views.py
from polls.models import Question, Choice
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.views import generic
from django.utils import timezone


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'
    
    def get_queryset(self):
        """
        Return the last five published questions(not including
        those set to be published in the future).
        """
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:5]

class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'
    
    def get_queryset(self):
        """ Excludes any questions that arent published yet"""
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


def vote(request, question_id):
    p = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = p.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': p,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(p.id,)))
    
def add(request, question_id):
    p = get_object_or_404(Question, pk=question_id)
    every = p.choice_set.all()
    
    try :
        selected_choice = request.POST['choice']
    except:
        return render(request, 'polls/detail.html', {
                    'question': p,
                    'error_message': "Please enter a viable answer!",
                     })
    else:
        if every.filter(choice_text=selected_choice).exists():
            return render(request, 'polls/detail.html', {
                    'question': p,
                    'error_message': "That answer choice is already there!",
                     })
        if selected_choice == '':
            return render(request, 'polls/detail.html', {
                'question': p,
                'error_message': "You didn't fill in an answer!",
                 })
        else:
            p.choice_set.create(choice_text=request.POST['choice'], votes=1)
            p.save()
            return HttpResponseRedirect(reverse('polls:results', args=(p.id,)))

def addq(request):
    p = Question.objects.all().order_by('-pub_date')
    
    try :
        selected_question = request.POST['question']
    except:
        return render(request, 'polls/index.html', {
                    'latest_question_list':p,
                    'error_message': "Please submit a question",
                     })
    else:
        if p.filter(question_text=selected_question).exists():
            return render(request, 'polls/index.html', {
                    'question':p,
                    'error_message': "That question is already there!",
                     })
        if selected_question == '':
            return render(request, 'polls/index.html', {
                'latest_question_list':p,
                'error_message': "You didn't fill in a question!",
                 })
        else:
            q= Question(question_text=request.POST['question'], pub_date=timezone.now())
            q.save()
            return render(request, 'polls/index.html', {
                    'latest_question_list':p,
                    'error_message': "Thanks for submitting a question!",
                     })
        

mysite/templates/views.py
from django.shortcuts import render

# Create your views here.

mysite/polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<input type="submit" value="Vote" />
</form>
<form action="{% url 'polls:add' question.id %}" method="post">
                {% csrf_token %}
                <input id="choice" type="text" placeholder="Add New Answer and vote!" name="choice" value="{{ choice.choice_text }}">
            </form>

mysite/polls/templates/polls/index.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />

<head>
    <title> Bezzist</title>
</head>




<body>
    <div class="header">
        <div class="container">
            <div class="logo">
                <h1> Bezzist</h1> 
            </div>
        </div>
    </div>
    
    <div class=container>
    
    <div class="content">
        <div class= error> {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}</div>
    {% if latest_question_list %}
        <ol>
        {% for question in latest_question_list %}
            <div class="choice"> 
            <h2 class="question" >{{ question.question_text }}</h2>
    
            {% if error_message1 %}<p><strong>{{ error_message1 }}</strong></p>{% endif %}
            
            <form action="{% url 'polls:vote' question.id %}" method="post">
                {% csrf_token %}
                {% for choice in question.choice_set.all %}
                
                    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
                    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
               
                {% endfor %}
                <input type="submit" value="Vote"s />
            </form>
            <form action="{% url 'polls:add' question.id %}" method="post">
                {% csrf_token %}
                <input id="choice" type="text" placeholder="Add New Answer and vote!" name="choice" value="{{ choice.choice_text }}">
            </form>
            </div>
        {% endfor %}
        </ol>
        <form action="{% url 'polls:addq' %}" method="post">
                {% csrf_token %}
                <input id="question" type="text" placeholder="Add a new Question!" name="question" value="{{ question.question_text }}">
        </form>
    </div>
    </div>
    {% else %}
        <p>No polls are available.</p>
    {% endif %}
</body>

mysite/polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="/polls/">Vote again?</a>